FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8888

ENV FLASK_APP=app.py
ENV FLASK_ENV=development

# This is so that the output is logged immediately
ENV PYTHONUNBUFFERED=1

CMD ["flask", "run", "--host=0.0.0.0", "--port=8888", "--reload"]

